### PR TITLE
let users make a wish

### LINKED ISSUE #3: Add a second box to the demo
I think it would be amazing if we could have an accompanying entry box after "Share your experience" that said something like "What do you wish had been different?" or "What do you wish your experience had been?"

That way folks don't just appear to complain all the time 😄 

The data should be captured along with the previous text, I don't think at this point we need an additional space to capture them separately.

@gedankenstuecke - do you have any time to implement that. Just say no if you're too busy and I'll see if I can have a play around....but I'm not super confident on where that would go in the code etc (and I don't have the local development set up yet!)

### PR DESCRIPTION
**Pull request by gedankenstuecke**
This allows users to add a wish of what they'd have liked to be different in their experience while submitting the experience. This data is stored in the JSON file on Open Humans. It also ends up in the local database if a member decides to make the data public.

The field is not mandatory, it can be left empty if users doesn't want to provide this data.

Closes #3

### CODE REVIEW

**Comment by KirstieJane** [comment]
Well - Travis doesn't seem to like it, but I think it looks awesome.

@GeorgiaHCA - are you able to review this today? You'll need to pull down @gedankenstuecke's branch and then run it locally on your machine.

**Comment by gedankenstuecke** [comment]
I'm currently fixing Travis, it fails as the dependencies that are used for actually running tests aren't part of the `Pipfile` 😂

**Comment by gedankenstuecke** [comment]
Okay, I also had to remove a lot of tests which were ancient relics of the demo repo we cloned. Basically all the tests that were gone are now implemented in the `django-open-humans` Python package that handles the API connections to Open Humans.

**Review by GeorgiaHCA — APPROVED** [review]
Hi Bastian, I love this make a wish idea :) thanks for creating it!

**Pull request merged**
